/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    announcements: Announcement;
    'home-slider': HomeSlider;
    'blog-posts': BlogPost;
    testimonials: Testimonial;
    coe: Coe;
    'coe-categories': CoeCategory;
    regulations: Regulation;
    'regulation-categories': RegulationCategory;
    departments: Department;
    'department-sections': DepartmentSection;
    'secondary-nav': SecondaryNav;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'home-slider': HomeSliderSelect<false> | HomeSliderSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    coe: CoeSelect<false> | CoeSelect<true>;
    'coe-categories': CoeCategoriesSelect<false> | CoeCategoriesSelect<true>;
    regulations: RegulationsSelect<false> | RegulationsSelect<true>;
    'regulation-categories': RegulationCategoriesSelect<false> | RegulationCategoriesSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    'department-sections': DepartmentSectionsSelect<false> | DepartmentSectionsSelect<true>;
    'secondary-nav': SecondaryNavSelect<false> | SecondaryNavSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    about: About;
    admissions: Admission;
    research: Research;
    placement: Placement;
    'international-relations': InternationalRelation;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    admissions: AdmissionsSelect<false> | AdmissionsSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    placement: PlacementSelect<false> | PlacementSelect<true>;
    'international-relations': InternationalRelationsSelect<false> | InternationalRelationsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'SuperAdmin' | 'Admin' | 'Blogger';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * User who uploaded this media
   */
  uploadedBy: string | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional link for "Read More" or call-to-action
   */
  link?: string | null;
  /**
   * Text to display for the link (e.g., "Read More", "Learn More")
   */
  linkText?: string | null;
  isActive?: boolean | null;
  /**
   * Higher numbers appear first
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-slider".
 */
export interface HomeSlider {
  id: string;
  title: string;
  /**
   * Desktop version - Recommended aspect ratio: 16:9
   */
  desktopImage: string | Media;
  /**
   * Mobile version - Recommended aspect ratio: 3:4
   */
  mobileImage?: (string | null) | Media;
  link?: string | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (string | null) | Media;
  /**
   * Author is automatically set to the current user
   */
  author: string | User;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  authorName: string;
  /**
   * e.g., "Student", "Faculty", "Alumni"
   */
  authorTitle?: string | null;
  authorImage?: (string | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coe".
 */
export interface Coe {
  id: string;
  /**
   * Title of the COE document
   */
  title: string;
  /**
   * Brief description of the document
   */
  description?: string | null;
  /**
   * Select the category for this document
   */
  category: string | CoeCategory;
  /**
   * Upload the PDF file for this COE document
   */
  pdfFile: string | Media;
  /**
   * Whether this document is active and visible
   */
  isActive?: boolean | null;
  /**
   * Higher numbers appear first within the category
   */
  priority?: number | null;
  /**
   * Number of times this document has been downloaded
   */
  downloadCount?: number | null;
  /**
   * Optional tags for better organization and searchability
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coe-categories".
 */
export interface CoeCategory {
  id: string;
  /**
   * Name of the COE category (e.g., "AI/ML", "IoT", "Cybersecurity")
   */
  name: string;
  /**
   * Brief description of what this category represents
   */
  description?: string | null;
  /**
   * Icon class or emoji for the category (optional)
   */
  icon?: string | null;
  /**
   * Whether this category is active and visible
   */
  isActive?: boolean | null;
  /**
   * Order of display (higher numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations".
 */
export interface Regulation {
  id: string;
  /**
   * Title of the regulation document
   */
  title: string;
  /**
   * Brief description of the regulation
   */
  description?: string | null;
  /**
   * Select the category for this regulation
   */
  category: string | RegulationCategory;
  /**
   * Upload the PDF file for this regulation document
   */
  pdfFile: string | Media;
  /**
   * Whether this regulation is active and visible
   */
  isActive?: boolean | null;
  /**
   * Higher numbers appear first within the category
   */
  priority?: number | null;
  /**
   * Number of times this regulation has been downloaded
   */
  downloadCount?: number | null;
  /**
   * Optional tags for better organization and searchability
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulation-categories".
 */
export interface RegulationCategory {
  id: string;
  /**
   * Name of the regulation category (e.g., "Academic Regulations", "Administrative Policies", "Student Guidelines")
   */
  name: string;
  /**
   * Brief description of what this category represents
   */
  description?: string | null;
  /**
   * Icon class or emoji for the category (optional)
   */
  icon?: string | null;
  /**
   * Whether this category is active and visible
   */
  isActive?: boolean | null;
  /**
   * Order of display (higher numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage departments for navigation dropdown
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: string;
  /**
   * Department name (e.g., Computer Science Engineering)
   */
  name: string;
  /**
   * Department code (e.g., CSE, ECE, MECH)
   */
  code: string;
  /**
   * URL slug (e.g., computer-science-engineering)
   */
  slug: string;
  /**
   * Short name for display in dropdown (optional)
   */
  shortName?: string | null;
  /**
   * Brief description of the department
   */
  description?: string | null;
  /**
   * Show in navigation dropdown
   */
  isActive?: boolean | null;
  /**
   * Display order in dropdown (higher numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "department-sections".
 */
export interface DepartmentSection {
  id: string;
  /**
   * Select the department this content belongs to
   */
  department: string | Department;
  /**
   * Internal title for this content section
   */
  title: string;
  /**
   * Whether this section is active and visible
   */
  isActive?: boolean | null;
  heroSection?: {
    /**
     * Main title for department page (defaults to department name)
     */
    heroTitle?: string | null;
    /**
     * Subtitle or tagline
     */
    heroSubtitle?: string | null;
    /**
     * Hero background image
     */
    heroImage?: (string | null) | Media;
    /**
     * Brief intro content for hero section
     */
    heroContent?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  introduction?: {
    /**
     * Introduction content for the department
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Featured image for introduction section
     */
    image?: (string | null) | Media;
  };
  peos?: {
    /**
     * Program Educational Objectives content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    objectives?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  pos?: {
    /**
     * Program Outcomes content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    outcomes?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  opportunities?: {
    /**
     * Career opportunities content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    opportunityList?:
      | {
          title: string;
          description?: string | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  labFacility?: {
    /**
     * Lab facilities overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    labs?:
      | {
          name: string;
          description: string;
          /**
           * List of equipment/software available
           */
          equipment?: string | null;
          images?:
            | {
                image: string | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faculty?: {
    /**
     * Faculty overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    facultyMembers?:
      | {
          name: string;
          designation: string;
          qualification?: string | null;
          specialization?: string | null;
          experience?: string | null;
          email?: string | null;
          phone?: string | null;
          image?: (string | null) | Media;
          bio?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  achievements?: {
    /**
     * Achievements overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    achievementList?:
      | {
          title: string;
          description: string;
          date?: string | null;
          category?: ('academic' | 'research' | 'student' | 'faculty' | 'awards' | 'other') | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  classroom?: {
    /**
     * Classroom facilities content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    classrooms?:
      | {
          name: string;
          capacity?: number | null;
          /**
           * List of facilities available in this classroom
           */
          facilities?: string | null;
          images?:
            | {
                image: string | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  facultyPublications?: {
    /**
     * Faculty publications overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    publications?:
      | {
          title: string;
          authors: string;
          journal?: string | null;
          conference?: string | null;
          year: number;
          type: 'journal' | 'conference' | 'book_chapter' | 'book' | 'patent' | 'other';
          /**
           * DOI or URL link to the publication
           */
          doi?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  guestLectures?: {
    /**
     * Guest lectures overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    lectures?:
      | {
          title: string;
          speaker: string;
          speakerDesignation?: string | null;
          organization?: string | null;
          date: string;
          description?: string | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  mous?: {
    /**
     * MoUs overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    mouList?:
      | {
          organization: string;
          purpose: string;
          dateOfSigning?: string | null;
          /**
           * Duration of the MoU (e.g., 3 years)
           */
          duration?: string | null;
          status?: ('active' | 'expired' | 'renewed') | null;
          /**
           * MoU document (PDF)
           */
          document?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  universityRankHolders?: {
    /**
     * University rank holders overview content
     */
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    rankHolders?:
      | {
          studentName: string;
          rank: number;
          /**
           * Academic year in format: 2024-25
           */
          academicYear: string;
          /**
           * Course/Program (e.g., B.E CSE, M.E CSE)
           */
          course: string;
          /**
           * CGPA/Percentage achieved
           */
          cgpa?: number | null;
          photo?: (string | null) | Media;
          /**
           * Current job/position of the student
           */
          currentPosition?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage secondary navigation bar buttons and their content pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "secondary-nav".
 */
export interface SecondaryNav {
  id: string;
  /**
   * Title/Label for the navigation button
   */
  title: string;
  /**
   * Optional description for admin reference
   */
  description?: string | null;
  /**
   * URL slug for this navigation item (e.g., admissions-portal, student-resources)
   */
  slug: string;
  /**
   * Choose whether this creates a content page or links to an external URL
   */
  linkType: 'content' | 'external';
  /**
   * Full external URL (e.g., https://google.com)
   */
  externalUrl?: string | null;
  /**
   * Content for the page this navigation button will create
   */
  pageContent?: {
    heroSection?: {
      /**
       * Main title for the page (defaults to nav title if empty)
       */
      heroTitle?: string | null;
      /**
       * Subtitle or tagline for the page
       */
      heroSubtitle?: string | null;
      /**
       * Hero background image
       */
      heroImage?: (string | null) | Media;
      /**
       * Rich text content for the hero section
       */
      heroContent?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    /**
     * Main content of the page
     */
    mainContent: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Add multiple content sections to build your page
     */
    contentSections?:
      | {
          /**
           * Title for this content section
           */
          sectionTitle: string;
          /**
           * Type of content section
           */
          sectionType: 'text' | 'gallery' | 'cards' | 'list' | 'accordion' | 'contact' | 'downloads';
          /**
           * Rich text content for this section
           */
          textContent?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          /**
           * Collection of images for gallery
           */
          imageGallery?:
            | {
                image: string | Media;
                /**
                 * Image caption
                 */
                caption?: string | null;
                /**
                 * Alt text for accessibility
                 */
                altText?: string | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Feature cards or highlight items
           */
          cardItems?:
            | {
                cardTitle: string;
                cardDescription?: {
                  root: {
                    type: string;
                    children: {
                      type: string;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                } | null;
                cardImage?: (string | null) | Media;
                /**
                 * Optional link for the card
                 */
                cardLink?: string | null;
                /**
                 * Icon class or emoji for the card
                 */
                cardIcon?: string | null;
                id?: string | null;
              }[]
            | null;
          /**
           * List of items with titles and descriptions
           */
          listItems?:
            | {
                itemTitle: string;
                itemDescription?: {
                  root: {
                    type: string;
                    children: {
                      type: string;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                } | null;
                /**
                 * Optional link for this item
                 */
                itemLink?: string | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Expandable accordion items (great for FAQs)
           */
          accordionItems?:
            | {
                /**
                 * Question or header text
                 */
                question: string;
                /**
                 * Answer or content that expands
                 */
                answer: {
                  root: {
                    type: string;
                    children: {
                      type: string;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                /**
                 * Whether this item should be expanded by default
                 */
                isOpenByDefault?: boolean | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Contact details section
           */
          contactInfo?: {
            email?: string | null;
            phone?: string | null;
            address?: string | null;
            workingHours?: string | null;
            /**
             * Google Maps embed code (iframe)
             */
            mapEmbedCode?: string | null;
          };
          /**
           * Downloadable files and documents
           */
          downloadLinks?:
            | {
                downloadTitle: string;
                downloadDescription?: string | null;
                downloadFile: string | Media;
                /**
                 * Category for grouping downloads
                 */
                downloadCategory?: string | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Order of this section (higher numbers appear first)
           */
          sectionOrder?: number | null;
          id?: string | null;
        }[]
      | null;
    seoSettings?: {
      /**
       * Page title for search engines (defaults to page title if empty)
       */
      metaTitle?: string | null;
      /**
       * Page description for search engines
       */
      metaDescription?: string | null;
      /**
       * SEO keywords (comma-separated)
       */
      keywords?: string | null;
      /**
       * Image for social media sharing
       */
      ogImage?: (string | null) | Media;
    };
  };
  /**
   * Open external links in a new tab
   */
  openInNewTab?: boolean | null;
  /**
   * Visual style of the button
   */
  buttonStyle?: ('primary' | 'secondary' | 'outline' | 'text' | 'warning' | 'info' | 'success' | 'danger') | null;
  /**
   * Optional icon class or emoji for the button (e.g., fa-home, 🏠)
   */
  icon?: string | null;
  /**
   * Position of the icon relative to text
   */
  iconPosition?: ('left' | 'right' | 'none') | null;
  /**
   * Whether this button is visible in the navigation
   */
  isVisible?: boolean | null;
  /**
   * Order of appearance (higher numbers appear first)
   */
  order?: number | null;
  /**
   * Control on which pages this button should appear
   */
  showOnPages?: ('all' | 'home' | 'internal' | 'specific')[] | null;
  /**
   * Define specific pages where this button should appear
   */
  specificPages?:
    | {
        /**
         * Page path (e.g., /about, /research, /admissions)
         */
        pagePath: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who can see this navigation button
   */
  accessLevel?: ('public' | 'students' | 'faculty' | 'admin') | null;
  scheduleSettings?: {
    /**
     * Enable time-based visibility for this button
     */
    isScheduled?: boolean | null;
    /**
     * Start date for button visibility
     */
    startDate?: string | null;
    /**
     * End date for button visibility (leave empty for no end date)
     */
    endDate?: string | null;
  };
  analytics?: {
    /**
     * Track clicks on this button for analytics
     */
    trackClicks?: boolean | null;
    /**
     * Total number of clicks (automatically updated)
     */
    clickCount?: number | null;
    /**
     * Custom Google Analytics event name for this button
     */
    googleAnalyticsEvent?: string | null;
  };
  additionalAttributes?: {
    /**
     * Additional CSS classes for custom styling
     */
    cssClass?: string | null;
    /**
     * Tooltip text that appears on hover
     */
    tooltip?: string | null;
    /**
     * Accessibility label for screen readers
     */
    ariaLabel?: string | null;
    /**
     * Custom data attributes for the button element
     */
    dataAttributes?:
      | {
          /**
           * Attribute name (without data- prefix)
           */
          key: string;
          /**
           * Attribute value
           */
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Internal notes about this navigation item (not visible to users)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'home-slider';
        value: string | HomeSlider;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'coe';
        value: string | Coe;
      } | null)
    | ({
        relationTo: 'coe-categories';
        value: string | CoeCategory;
      } | null)
    | ({
        relationTo: 'regulations';
        value: string | Regulation;
      } | null)
    | ({
        relationTo: 'regulation-categories';
        value: string | RegulationCategory;
      } | null)
    | ({
        relationTo: 'departments';
        value: string | Department;
      } | null)
    | ({
        relationTo: 'department-sections';
        value: string | DepartmentSection;
      } | null)
    | ({
        relationTo: 'secondary-nav';
        value: string | SecondaryNav;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  link?: T;
  linkText?: T;
  isActive?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-slider_select".
 */
export interface HomeSliderSelect<T extends boolean = true> {
  title?: T;
  desktopImage?: T;
  mobileImage?: T;
  link?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorTitle?: T;
  authorImage?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coe_select".
 */
export interface CoeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  pdfFile?: T;
  isActive?: T;
  priority?: T;
  downloadCount?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coe-categories_select".
 */
export interface CoeCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations_select".
 */
export interface RegulationsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  pdfFile?: T;
  isActive?: T;
  priority?: T;
  downloadCount?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulation-categories_select".
 */
export interface RegulationCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  slug?: T;
  shortName?: T;
  description?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "department-sections_select".
 */
export interface DepartmentSectionsSelect<T extends boolean = true> {
  department?: T;
  title?: T;
  isActive?: T;
  heroSection?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        heroImage?: T;
        heroContent?: T;
      };
  introduction?:
    | T
    | {
        content?: T;
        image?: T;
      };
  peos?:
    | T
    | {
        content?: T;
        objectives?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pos?:
    | T
    | {
        content?: T;
        outcomes?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  opportunities?:
    | T
    | {
        content?: T;
        opportunityList?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  labFacility?:
    | T
    | {
        content?: T;
        labs?:
          | T
          | {
              name?: T;
              description?: T;
              equipment?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faculty?:
    | T
    | {
        content?: T;
        facultyMembers?:
          | T
          | {
              name?: T;
              designation?: T;
              qualification?: T;
              specialization?: T;
              experience?: T;
              email?: T;
              phone?: T;
              image?: T;
              bio?: T;
              id?: T;
            };
      };
  achievements?:
    | T
    | {
        content?: T;
        achievementList?:
          | T
          | {
              title?: T;
              description?: T;
              date?: T;
              category?: T;
              image?: T;
              id?: T;
            };
      };
  classroom?:
    | T
    | {
        content?: T;
        classrooms?:
          | T
          | {
              name?: T;
              capacity?: T;
              facilities?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  facultyPublications?:
    | T
    | {
        content?: T;
        publications?:
          | T
          | {
              title?: T;
              authors?: T;
              journal?: T;
              conference?: T;
              year?: T;
              type?: T;
              doi?: T;
              id?: T;
            };
      };
  guestLectures?:
    | T
    | {
        content?: T;
        lectures?:
          | T
          | {
              title?: T;
              speaker?: T;
              speakerDesignation?: T;
              organization?: T;
              date?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  mous?:
    | T
    | {
        content?: T;
        mouList?:
          | T
          | {
              organization?: T;
              purpose?: T;
              dateOfSigning?: T;
              duration?: T;
              status?: T;
              document?: T;
              id?: T;
            };
      };
  universityRankHolders?:
    | T
    | {
        content?: T;
        rankHolders?:
          | T
          | {
              studentName?: T;
              rank?: T;
              academicYear?: T;
              course?: T;
              cgpa?: T;
              photo?: T;
              currentPosition?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "secondary-nav_select".
 */
export interface SecondaryNavSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  linkType?: T;
  externalUrl?: T;
  pageContent?:
    | T
    | {
        heroSection?:
          | T
          | {
              heroTitle?: T;
              heroSubtitle?: T;
              heroImage?: T;
              heroContent?: T;
            };
        mainContent?: T;
        contentSections?:
          | T
          | {
              sectionTitle?: T;
              sectionType?: T;
              textContent?: T;
              imageGallery?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    altText?: T;
                    id?: T;
                  };
              cardItems?:
                | T
                | {
                    cardTitle?: T;
                    cardDescription?: T;
                    cardImage?: T;
                    cardLink?: T;
                    cardIcon?: T;
                    id?: T;
                  };
              listItems?:
                | T
                | {
                    itemTitle?: T;
                    itemDescription?: T;
                    itemLink?: T;
                    id?: T;
                  };
              accordionItems?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    isOpenByDefault?: T;
                    id?: T;
                  };
              contactInfo?:
                | T
                | {
                    email?: T;
                    phone?: T;
                    address?: T;
                    workingHours?: T;
                    mapEmbedCode?: T;
                  };
              downloadLinks?:
                | T
                | {
                    downloadTitle?: T;
                    downloadDescription?: T;
                    downloadFile?: T;
                    downloadCategory?: T;
                    id?: T;
                  };
              sectionOrder?: T;
              id?: T;
            };
        seoSettings?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              keywords?: T;
              ogImage?: T;
            };
      };
  openInNewTab?: T;
  buttonStyle?: T;
  icon?: T;
  iconPosition?: T;
  isVisible?: T;
  order?: T;
  showOnPages?: T;
  specificPages?:
    | T
    | {
        pagePath?: T;
        id?: T;
      };
  accessLevel?: T;
  scheduleSettings?:
    | T
    | {
        isScheduled?: T;
        startDate?: T;
        endDate?: T;
      };
  analytics?:
    | T
    | {
        trackClicks?: T;
        clickCount?: T;
        googleAnalyticsEvent?: T;
      };
  additionalAttributes?:
    | T
    | {
        cssClass?: T;
        tooltip?: T;
        ariaLabel?: T;
        dataAttributes?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
            };
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage About page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  /**
   * Main hero title for the about page
   */
  heroTitle: string;
  /**
   * Hero subtitle displayed below the main title
   */
  heroSubtitle?: string | null;
  /**
   * Hero banner image for the about page
   */
  heroImage?: (string | null) | Media;
  sections?:
    | {
        /**
         * Title of the section
         */
        title: string;
        /**
         * Choose the type of content for this section
         */
        contentType?: ('richText' | 'table' | 'dynamicTable' | 'mixed' | 'mixedDynamic') | null;
        /**
         * Rich text content for this section
         */
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Table data with labels and links
         */
        tableData?:
          | {
              /**
               * Display text for the table row
               */
              label: string;
              /**
               * URL or file path for the link
               */
              link: string;
              /**
               * Check if this is an external link (opens in new tab)
               */
              isExternal?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Configure a custom table with multiple columns
         */
        dynamicTableConfig?: {
          columns: {
            /**
             * Unique identifier for this column (no spaces, use camelCase)
             */
            key: string;
            /**
             * Display label for the column header
             */
            label: string;
            /**
             * Optional CSS width (e.g., "w-20", "w-1/4")
             */
            width?: string | null;
            id?: string | null;
          }[];
          rows: {
            /**
             * Row data as JSON object. Keys should match column keys.
             */
            data?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
          }[];
          /**
           * Visual style of the table
           */
          variant?: ('default' | 'bordered' | 'striped') | null;
        };
        /**
         * Optional custom title for the table (defaults to "Table Title")
         */
        tableTitle?: string | null;
        /**
         * Optional image for this section
         */
        image?: (string | null) | Media;
        /**
         * Order of display (lower numbers appear first)
         */
        order?: number | null;
        /**
         * Whether this section is active and visible
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions".
 */
export interface Admission {
  id: string;
  /**
   * Main hero title for the about page
   */
  heroTitle: string;
  /**
   * Hero subtitle displayed below the main title
   */
  heroSubtitle?: string | null;
  /**
   * Hero banner image for the about page
   */
  heroImage?: (string | null) | Media;
  sections?:
    | {
        /**
         * Title of the about section
         */
        title: string;
        /**
         * Content for this about section
         */
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional image for this section
         */
        image?: (string | null) | Media;
        /**
         * Order of display (lower numbers appear first)
         */
        order?: number | null;
        /**
         * Whether this section is active and visible
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Research page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: string;
  /**
   * Main hero title for the research page
   */
  heroTitle: string;
  /**
   * Hero subtitle displayed below the main title
   */
  heroSubtitle?: string | null;
  /**
   * Hero banner image for the research page
   */
  heroImage?: (string | null) | Media;
  sections?:
    | {
        /**
         * Title of the section
         */
        title: string;
        /**
         * Choose the type of content for this section
         */
        contentType?: ('richText' | 'table' | 'dynamicTable' | 'mixed' | 'mixedDynamic') | null;
        /**
         * Rich text content for this section
         */
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Table data with labels and links
         */
        tableData?:
          | {
              /**
               * Display text for the table row
               */
              label: string;
              /**
               * URL or file path for the link
               */
              link: string;
              /**
               * Check if this is an external link (opens in new tab)
               */
              isExternal?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Configure a custom table with multiple columns
         */
        dynamicTableConfig?: {
          columns: {
            /**
             * Unique identifier for this column (no spaces, use camelCase)
             */
            key: string;
            /**
             * Display label for the column header
             */
            label: string;
            /**
             * Optional CSS width (e.g., "w-20", "w-1/4")
             */
            width?: string | null;
            id?: string | null;
          }[];
          rows: {
            /**
             * Row data as JSON object. Keys should match column keys.
             */
            data?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
          }[];
          /**
           * Visual style of the table
           */
          variant?: ('default' | 'bordered' | 'striped') | null;
        };
        /**
         * Optional custom title for the table (defaults to "Table Title")
         */
        tableTitle?: string | null;
        /**
         * Optional image for this section
         */
        image?: (string | null) | Media;
        /**
         * Order of display (lower numbers appear first)
         */
        order?: number | null;
        /**
         * Whether this section is active and visible
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Placement page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement".
 */
export interface Placement {
  id: string;
  /**
   * Main hero title for the placement page
   */
  heroTitle: string;
  /**
   * Hero subtitle displayed below the main title
   */
  heroSubtitle?: string | null;
  /**
   * Hero banner image for the placement page
   */
  heroImage?: (string | null) | Media;
  sections?:
    | {
        /**
         * Title of the section
         */
        title: string;
        /**
         * Choose the type of content for this section
         */
        contentType?: ('richText' | 'table' | 'dynamicTable' | 'mixed' | 'mixedDynamic') | null;
        /**
         * Rich text content for this section
         */
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Table data with labels and links
         */
        tableData?:
          | {
              /**
               * Display text for the table row
               */
              label: string;
              /**
               * URL or file path for the link
               */
              link: string;
              /**
               * Check if this is an external link (opens in new tab)
               */
              isExternal?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Configure a custom table with multiple columns
         */
        dynamicTableConfig?: {
          columns: {
            /**
             * Unique identifier for this column (no spaces, use camelCase)
             */
            key: string;
            /**
             * Display label for the column header
             */
            label: string;
            /**
             * Optional CSS width (e.g., "w-20", "w-1/4")
             */
            width?: string | null;
            id?: string | null;
          }[];
          rows: {
            /**
             * Row data as JSON object. Keys should match column keys.
             */
            data?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
          }[];
          /**
           * Visual style of the table
           */
          variant?: ('default' | 'bordered' | 'striped') | null;
        };
        /**
         * Optional custom title for the table (defaults to "Table Title")
         */
        tableTitle?: string | null;
        /**
         * Optional image for this section
         */
        image?: (string | null) | Media;
        /**
         * Order of display (lower numbers appear first)
         */
        order?: number | null;
        /**
         * Whether this section is active and visible
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-relations".
 */
export interface InternationalRelation {
  id: string;
  /**
   * Main hero title for the about page
   */
  heroTitle: string;
  /**
   * Hero subtitle displayed below the main title
   */
  heroSubtitle?: string | null;
  /**
   * Hero banner image for the about page
   */
  heroImage?: (string | null) | Media;
  sections?:
    | {
        /**
         * Title of the about section
         */
        title: string;
        /**
         * Content for this about section
         */
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional image for this section
         */
        image?: (string | null) | Media;
        /**
         * Order of display (lower numbers appear first)
         */
        order?: number | null;
        /**
         * Whether this section is active and visible
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  sections?:
    | T
    | {
        title?: T;
        contentType?: T;
        content?: T;
        tableData?:
          | T
          | {
              label?: T;
              link?: T;
              isExternal?: T;
              id?: T;
            };
        dynamicTableConfig?:
          | T
          | {
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    width?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              variant?: T;
            };
        tableTitle?: T;
        image?: T;
        order?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions_select".
 */
export interface AdmissionsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
        order?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  sections?:
    | T
    | {
        title?: T;
        contentType?: T;
        content?: T;
        tableData?:
          | T
          | {
              label?: T;
              link?: T;
              isExternal?: T;
              id?: T;
            };
        dynamicTableConfig?:
          | T
          | {
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    width?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              variant?: T;
            };
        tableTitle?: T;
        image?: T;
        order?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement_select".
 */
export interface PlacementSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  sections?:
    | T
    | {
        title?: T;
        contentType?: T;
        content?: T;
        tableData?:
          | T
          | {
              label?: T;
              link?: T;
              isExternal?: T;
              id?: T;
            };
        dynamicTableConfig?:
          | T
          | {
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    width?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              variant?: T;
            };
        tableTitle?: T;
        image?: T;
        order?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-relations_select".
 */
export interface InternationalRelationsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
        order?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}